#!/bin/sh
# Installs the tools this course's labs use, at the versions of the LearnSome.tech lab sandbox, on x86-64
# Ubuntu: the dev container (Dockerfile) and CI (.github/workflows/check.yml) both run it, as root.
# `install-tools.sh ci` leaves out the Linux userland the labs call, which CI does not need.
# Generated by the LearnSome.tech platform (scripts/labs-repos); do not edit here.
set -eu
if [ "$(uname -m)" != x86_64 ]; then
  echo "install-tools.sh: x86-64 Linux only (Codespaces, GitHub Actions); elsewhere install the tools yourself" >&2
  exit 1
fi
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
fetch() { curl -fsSL --retry 3 "$1" -o "$2" && echo "$3  $2" | sha256sum -c - >/dev/null; }

export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get install -y -q --no-install-recommends bash git unzip xz-utils ca-certificates curl
rm -rf /var/lib/apt/lists/*
mkdir -p /opt/lab

# Node.js 24.21.0
fetch 'https://nodejs.org/dist/v24.21.0/node-v24.21.0-linux-x64.tar.xz' "$tmp/node.txz" fd8e59d5a511510f6a298afb548f18c7d2b1be404d8b4a27d94fbe49f56cb2d6
mkdir -p /opt/node && tar -xJf "$tmp/node.txz" -C /opt/node --strip-components=1
for t in node npm npx; do ln -sf "/opt/node/bin/$t" "/usr/local/bin/$t"; done
