// The lab checker of a LearnSome.tech labs repository (run it through ./check).
//
// It runs a lab the way the site's lab sandbox does (workers/labs/run_lab.py on the platform): the starter
// files copied into a scratch directory that is the program's working directory and HOME, TMPDIR in a
// scratch directory of its own, LANG=C.UTF-8 and TZ=UTC, input.txt on stdin, a 10 second limit and 256 KiB
// of output per stream. The output is graded with the site's own comparison (grading.mjs is the platform's
// grader, copied unchanged). Generated by the LearnSome.tech platform (scripts/labs-repos); do not edit here.
import { spawn, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { gradeOutput } from './grading.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const COURSE = JSON.parse(fs.readFileSync(path.join(ROOT, '.learnsome', 'course.json'), 'utf8'));
const TIMEOUT_MS = COURSE.limits.timeoutSeconds * 1000;
const OUTPUT_CAP = COURSE.limits.outputBytes;
const LAB_FILES = new Set(['README.md', 'check.json', 'expected.txt', 'starter']);
const MODES = new Set(['graded', 'run', 'checker', 'read-along']);
const color = process.stdout.isTTY && !process.env.NO_COLOR;
const paint = (code, text) => (color ? `\u001b[${code}m${text}\u001b[0m` : text);
const STATUS = {
  PASS: paint('32', 'PASS'), FAIL: paint('31', 'FAIL'), RAN: paint('36', 'RAN '), SKIP: paint('33', 'SKIP'),
  'NO TOOL': paint('35', 'NO TOOL'),
};

// ---------- labs ----------

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

const manifest = () => readJson(path.join(ROOT, '.learnsome', 'labs.json'));

function loadLab(entry) {
  const dir = path.join(ROOT, entry.dir);
  return { ...readJson(path.join(dir, 'check.json')), dir, relDir: entry.dir };
}

/** Labs named on the command line: a lab id (m01l01-02), a lesson id (m01l01) or a path in a lab. */
function select(names) {
  const entries = manifest();
  const picked = [];
  for (const name of names) {
    const rel = path.relative(ROOT, path.resolve(name)).split(path.sep).join('/');
    const found = entries.filter((e) => e.lab === name || e.lesson === name || rel === e.dir || rel.startsWith(`${e.dir}/`));
    if (!found.length) {
      console.error(`check: no lab called ${name} (./check --list shows them)`);
      process.exit(2);
    }
    picked.push(...found);
  }
  return [...new Map(picked.map((e) => [e.dir, e])).values()];
}

// ---------- tools ----------

const localBin = path.join(ROOT, 'node_modules', '.bin');
const searchPath = [localBin, ...(process.env.PATH ?? '').split(path.delimiter)].join(path.delimiter);

function which(tool) {
  for (const dir of searchPath.split(path.delimiter)) {
    if (!dir) continue;
    const file = path.join(dir, tool);
    try {
      fs.accessSync(file, fs.constants.X_OK);
      if (fs.statSync(file).isFile()) return file;
    } catch {}
  }
  return null;
}

const missingTools = (lab) => (lab.requires ?? []).filter((tool) => !which(tool));

let goCache;
function goEnv() {
  if (goCache === undefined) {
    const out = spawnSync('go', ['env', 'GOCACHE'], { encoding: 'utf8', env: { ...process.env, PATH: searchPath } });
    goCache = process.env.GOCACHE || (out.status === 0 ? out.stdout.trim() : '');
  }
  return {
    GOTOOLCHAIN: 'local', GOPROXY: 'off', GOSUMDB: 'off', CGO_ENABLED: '0', GOFLAGS: '-buildvcs=false',
    ...(goCache ? { GOCACHE: goCache } : {}),
  };
}

/** The Kubernetes schemas the site validates against: fetched once, checked against their SHA-256 sums. */
function kubeSchemas() {
  const k8s = COURSE.kubeconform;
  const dir = process.env.LEARNSOME_K8S_SCHEMAS || path.join(ROOT, '.learnsome', 'cache', 'k8s-schemas');
  fs.mkdirSync(dir, { recursive: true });
  for (const [sum, name] of k8s.schemas) {
    const file = path.join(dir, name);
    const ok = () => fs.existsSync(file) && createHash('sha256').update(fs.readFileSync(file)).digest('hex') === sum;
    if (ok()) continue;
    const got = spawnSync('curl', ['-fsSL', `${k8s.url}/${name}`, '-o', file], { stdio: 'inherit' });
    if (got.status !== 0 || !ok()) throw new Error(`could not fetch the Kubernetes schema ${name}`);
  }
  return dir;
}

const TERRAFORM = 'if ls ./*.tf >/dev/null 2>&1; then terraform init -input=false -no-color >/dev/null 2>&1; fi; exec sh "$1"';
const TERRAFORM_VALIDATE = 'out=$(terraform init -backend=false -input=false -no-color 2>&1) || { printf "%s\\n" "$out"; exit 1; }; exec terraform validate -no-color';
const SQL_WITH_FIXTURES = 'db=$1; shift; for f in "$@"; do sqlite3 "$db" < "$f"; done; exec sqlite3 -header -column "$db"';
const NODE_TS = ['node', '--experimental-transform-types', '--disable-warning=ExperimentalWarning'];

function terraformEnv() {
  const env = { CHECKPOINT_DISABLE: '1', TF_IN_AUTOMATION: '1', GOMAXPROCS: '2' };
  for (const c of ['init', 'plan', 'apply', 'destroy', 'validate', 'refresh', 'output', 'show', 'import', 'fmt', 'test', 'get']) {
    env[`TF_CLI_ARGS_${c}`] = '-no-color';
  }
  if (fs.existsSync(COURSE.terraformMirror)) env.TF_CLI_CONFIG_FILE = COURSE.terraformMirror;
  return env;
}

const ANSIBLE_ENV = {
  ANSIBLE_NOCOLOR: '1', ANSIBLE_LOCALHOST_WARNING: 'False', ANSIBLE_DEPRECATION_WARNINGS: 'False',
};

/** argv, whether the program goes to stdin, and extra environment: run_lab.py's command_for(). */
function commandFor(lab, home, tmp) {
  const f = lab.main;
  switch (lab.runner) {
    case 'python': return [['python3', f], false, {}];
    case 'bash': return [['bash', f], false, {}];
    case 'node': return [['node', f], false, {}];
    case 'node-ts': return [[...NODE_TS, f], false, {}];
    case 'tsx': return [['tsx', f], false, {}];
    case 'recorded': return [['bash', fs.existsSync(path.join(home, 'run.sh')) ? 'run.sh' : 'command.txt'], false, {}];
    case 'hadolint': return [['hadolint', '--no-color', '--failure-threshold', 'error', f], false, {}];
    case 'kubeconform': {
      const schemas = kubeSchemas();
      return [['kubeconform', '-strict', '-summary', '-output', 'text', '-ignore-missing-schemas', '-schema-location', `${schemas}/{{.ResourceKind}}{{.KindSuffix}}.json`, f], false, {}];
    }
    case 'actionlint': return [['actionlint', '-no-color', '-shellcheck=', '-pyflakes=', f], false, {}];
    case 'yamllint': return [['yamllint', '-d', 'relaxed', '-f', 'standard', f], false, {}];
    case 'ansible-syntax': return [['ansible-playbook', '--syntax-check', '-i', 'localhost,', '-c', 'local', f], false, ANSIBLE_ENV];
    case 'terraform-validate': return [['sh', '-c', TERRAFORM_VALIDATE], false, terraformEnv()];
    case 'java': return [['java', `-Djava.io.tmpdir=${tmp}`, f], false, {}];
    case 'go': return [['go', 'run', fs.existsSync(path.join(home, 'go.mod')) ? '.' : f], false, goEnv()];
    case 'sqlite': {
      const fixtures = fs.readdirSync(home).filter((n) => n.toLowerCase().endsWith('.sql') && n !== f && fs.statSync(path.join(home, n)).isFile()).sort();
      if (!fixtures.length) return [['sqlite3', '-header', '-column', ':memory:'], true, {}];
      return [['bash', '-c', SQL_WITH_FIXTURES, 'seed', `${fixtures[0].replace(/\.[^.]*$/, '')}.db`, ...fixtures], true, {}];
    }
    case 'terraform': {
      const script = fs.existsSync(path.join(home, 'cmd.sh')) ? 'cmd.sh' : f;
      return [['sh', '-c', TERRAFORM, 'terraform-lab', script], false, { ...terraformEnv(), ...ANSIBLE_ENV }];
    }
    default: throw new Error(`no runner ${lab.runner}`);
  }
}

// Variables passed through from your shell, beyond the sandbox's own (toolchains that find themselves by them).
const PASS_THROUGH = ['JAVA_HOME', 'GOROOT', 'SSL_CERT_FILE', 'SYSTEMROOT'];

/** Copies the lab's files into a scratch directory, runs it and returns run_lab.py's result shape. */
async function execute(lab) {
  const base = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'learnsome-lab-')));
  const home = path.join(base, 'work'); // the program's directory, named as on the site
  const tmp = path.join(base, 'tmp');
  fs.mkdirSync(home);
  fs.mkdirSync(tmp);
  try {
    for (const name of lab.files) {
      const target = path.join(home, name);
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.copyFileSync(path.join(lab.dir, 'starter', name), target);
      fs.chmodSync(target, 0o644); // as the sandbox writes them: not executable
    }
    for (const { path: name, from } of lab.shared ?? []) {
      const target = path.join(home, name);
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.copyFileSync(path.join(ROOT, from), target);
      fs.chmodSync(target, 0o644);
    }
    if (['node', 'node-ts', 'tsx'].includes(lab.runner) && !fs.existsSync(path.join(home, 'node_modules')) && fs.existsSync(path.join(ROOT, 'node_modules'))) {
      fs.symlinkSync(path.join(ROOT, 'node_modules'), path.join(home, 'node_modules'));
    }
    if (lab.runner === 'tsx' && !fs.existsSync(path.join(home, 'package.json'))) {
      fs.writeFileSync(path.join(base, 'package.json'), '{"type": "module"}\n');
    }
    const [argv, codeOnStdin, extraEnv] = commandFor(lab, home, tmp);
    const stdin = codeOnStdin
      ? fs.readFileSync(path.join(home, lab.main))
      : lab.stdin ? fs.readFileSync(path.join(lab.dir, 'starter', lab.stdin)) : Buffer.alloc(0);
    const env = { LANG: 'C.UTF-8', TZ: 'UTC', HOME: home, PATH: searchPath, TMPDIR: tmp, ...extraEnv };
    for (const key of PASS_THROUGH) if (process.env[key] && !env[key]) env[key] = process.env[key];
    // mergeStderr: stderr into stdout (2>&1), in the order it was written, as for labs recorded that way.
    const run = lab.mergeStderr ? ['sh', '-c', 'exec "$@" 2>&1', 'sh', ...argv] : argv;
    const result = await spawnCapped(run, { cwd: home, env }, stdin);
    // Paths as the site shows them: the program's directory as /work (relative before a file name), its
    // scratch space as /tmp.
    const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    for (const key of ['stdout', 'stderr']) {
      let text = result[key];
      text = text.replace(new RegExp(`(?<![\\w./-])${esc(home)}/`, 'g'), '');
      text = text.replace(new RegExp(`(?<![\\w./-])${esc(home)}(?![\\w.-])`, 'g'), '/work');
      result[key] = text.replace(new RegExp(`(?<![\\w./-])${esc(tmp)}(?![\\w.-])`, 'g'), '/tmp');
    }
    return result;
  } finally {
    fs.rmSync(base, { recursive: true, force: true });
  }
}

function spawnCapped(argv, options, stdin) {
  return new Promise((resolve) => {
    const started = Date.now();
    const child = spawn(argv[0], argv.slice(1), { ...options, detached: true, stdio: ['pipe', 'pipe', 'pipe'] });
    const out = { stdout: { chunks: [], size: 0, truncated: false }, stderr: { chunks: [], size: 0, truncated: false } };
    let timedOut = false;
    let stoppedAt = null;
    const killAll = () => {
      try { process.kill(-child.pid, 'SIGKILL'); } catch {}
    };
    const timer = setTimeout(() => {
      timedOut = true;
      stoppedAt ??= Date.now();
      killAll();
    }, TIMEOUT_MS);
    for (const key of ['stdout', 'stderr']) {
      child[key].on('data', (chunk) => {
        const buf = out[key];
        const room = OUTPUT_CAP - buf.size;
        if (chunk.length > room) {
          chunk = chunk.subarray(0, room);
          buf.truncated = true;
        }
        if (chunk.length) {
          buf.chunks.push(chunk);
          buf.size += chunk.length;
        }
        if (buf.truncated) {
          stoppedAt ??= Date.now();
          killAll();
        }
      });
    }
    child.stdin.on('error', () => {});
    child.stdin.end(stdin);
    child.on('error', (err) => {
      clearTimeout(timer);
      resolve({ exitCode: 127, stdout: '', stderr: `${argv[0]}: ${err.message}\n`, durationMs: 0, timedOut: false, truncated: false });
    });
    child.on('close', (code, signal) => {
      clearTimeout(timer);
      killAll(); // anything the program left running goes with it
      const exitCode = signal ? 128 + (os.constants.signals[signal] ?? 9) : code ?? 137;
      resolve({
        exitCode,
        stdout: Buffer.concat(out.stdout.chunks).toString('utf8'),
        stderr: Buffer.concat(out.stderr.chunks).toString('utf8'),
        durationMs: (stoppedAt ?? Date.now()) - started,
        timedOut,
        truncated: out.stdout.truncated || out.stderr.truncated,
      });
    });
  });
}

// ---------- checking ----------

function showDiff(diff) {
  const shown = diff.slice(0, 20);
  for (const d of shown) {
    console.log(`    line ${d.line}:`);
    console.log(`      expected: ${d.expected === null ? '(nothing)' : JSON.stringify(d.expected)}`);
    console.log(`      got:      ${d.actual === null ? '(nothing)' : JSON.stringify(d.actual)}`);
  }
  if (diff.length > shown.length) console.log(`    … ${diff.length - shown.length} more differing lines`);
}

function showOutput(result) {
  const text = `${result.stdout}${result.stderr ? (result.stdout && !result.stdout.endsWith('\n') ? '\n' : '') + result.stderr : ''}`;
  if (!text) return;
  for (const line of text.replace(/\n$/, '').split('\n')) console.log(`    | ${line}`);
}

/** Runs one lab: 'pass', 'fail', 'ran', 'skip' or 'notool'. */
async function checkLab(lab, { verbose }) {
  const label = `${lab.lab}  ${lab.title}`;
  if (lab.mode === 'read-along') {
    console.log(`${STATUS.SKIP}  ${label}\n    read along: ${lab.note}`);
    return 'skip';
  }
  const missing = missingTools(lab);
  if (missing.length) {
    console.log(`${STATUS['NO TOOL']}  ${label}\n    needs ${missing.join(', ')} on your PATH (the dev container has them)`);
    return 'notool';
  }
  const result = await execute(lab);
  const limits = [result.timedOut && `stopped after ${COURSE.limits.timeoutSeconds} s`, result.truncated && 'output over the size limit'].filter(Boolean);
  if (lab.mode === 'checker') {
    const ok = result.exitCode === 0 && !result.timedOut;
    console.log(`${ok ? STATUS.PASS : STATUS.FAIL}  ${label}\n    ${lab.command}: exit ${result.exitCode}${limits.length ? ` (${limits.join(', ')})` : ''}`);
    if (!ok || verbose) showOutput(result);
    return ok ? 'pass' : 'fail';
  }
  if (lab.mode === 'run') {
    console.log(`${STATUS.RAN}  ${label}\n    ${lab.command}: exit ${result.exitCode}${limits.length ? ` (${limits.join(', ')})` : ''}; not graded: ${lab.note}`);
    if (verbose) showOutput(result);
    return 'ran';
  }
  const expected = fs.readFileSync(path.join(lab.dir, lab.expected), 'utf8');
  const graded = gradeOutput(result.stdout, result.stderr, expected, { grading: lab.grading });
  const passed = graded.passed && !result.timedOut && !result.truncated;
  console.log(`${passed ? STATUS.PASS : STATUS.FAIL}  ${label}`);
  if (!passed) {
    if (limits.length) console.log(`    ${limits.join(', ')}`);
    if (graded.diff.length) {
      console.log(`    output differs from ${path.join(lab.relDir, lab.expected)}:`);
      showDiff(graded.diff);
    }
  } else if (verbose) {
    showOutput(result);
  }
  return passed ? 'pass' : 'fail';
}

// ---------- lint (what CI runs) ----------

function lintStructure(problems) {
  const entries = manifest();
  const known = new Set(entries.map((e) => e.dir));
  const lessonDirs = new Set(entries.map((e) => path.dirname(e.dir)));
  for (const lessonDir of lessonDirs) {
    if (!fs.existsSync(path.join(ROOT, lessonDir, 'README.md'))) problems.push(`${lessonDir}: no README.md`);
    for (const name of fs.readdirSync(path.join(ROOT, lessonDir))) {
      const rel = `${lessonDir}/${name}`;
      if (name !== 'README.md' && !known.has(rel)) problems.push(`${rel}: not a lab of this course`);
    }
  }
  for (const name of fs.readdirSync(path.join(ROOT, 'labs'))) {
    if (!lessonDirs.has(`labs/${name}`)) problems.push(`labs/${name}: not a lesson of this course`);
  }
  for (const entry of entries) {
    const dir = path.join(ROOT, entry.dir);
    const where = entry.dir;
    if (!fs.existsSync(path.join(dir, 'README.md'))) problems.push(`${where}: no README.md`);
    let lab;
    try {
      lab = loadLab(entry);
    } catch (err) {
      problems.push(`${where}/check.json: ${err.code === 'ENOENT' ? 'missing' : err.message}`);
      continue;
    }
    if (lab.lab !== entry.lab) problems.push(`${where}/check.json: lab is ${lab.lab}, expected ${entry.lab}`);
    if (!MODES.has(lab.mode)) problems.push(`${where}/check.json: unknown mode ${lab.mode}`);
    if (lab.mode !== 'read-along' && !lab.runner) problems.push(`${where}/check.json: no runner`);
    if ((lab.mode === 'read-along' || lab.mode === 'run') && !lab.note) problems.push(`${where}/check.json: no note`);
    for (const name of fs.readdirSync(dir)) if (!LAB_FILES.has(name)) problems.push(`${where}/${name}: not part of the lab`);
    if (lab.mode === 'graded') {
      if (!lab.expected || !fs.existsSync(path.join(dir, lab.expected))) problems.push(`${where}: graded but has no expected output`);
      if (!lab.grading) problems.push(`${where}/check.json: graded without a grading rule`);
    } else if (fs.existsSync(path.join(dir, 'expected.txt'))) {
      problems.push(`${where}/expected.txt: only graded labs have expected output`);
    }
    const files = new Set(lab.files ?? []);
    if (!files.has(lab.main)) problems.push(`${where}/check.json: main file ${lab.main} is not listed`);
    for (const name of files) if (!fs.existsSync(path.join(dir, 'starter', name))) problems.push(`${where}/starter/${name}: missing`);
    for (const name of listFiles(path.join(dir, 'starter'))) if (!files.has(name)) problems.push(`${where}/starter/${name}: not listed in check.json`);
    if (lab.stdin && !files.has(lab.stdin)) problems.push(`${where}/check.json: stdin file ${lab.stdin} is not a starter file`);
    for (const s of lab.shared ?? []) if (!fs.existsSync(path.join(ROOT, s.from))) problems.push(`${where}: shared file ${s.from} missing`);
  }
  for (const lessonDir of lessonDirs) {
    for (const name of fs.readdirSync(path.join(ROOT, lessonDir))) {
      const rel = `${lessonDir}/${name}`;
      if (known.has(rel) && !fs.statSync(path.join(ROOT, rel)).isDirectory()) problems.push(`${rel}: not a directory`);
    }
  }
}

function listFiles(dir, base = dir) {
  if (!fs.existsSync(dir)) return [];
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(full, base));
    else out.push(path.relative(base, full).split(path.sep).join('/'));
  }
  return out;
}

/** The parse check for a starter file of a lab, by the lab's runner: [tool, argv] or null. */
const SYNTAX = {
  '.py': (file) => ['python3', ['-c', 'import ast,sys\nfor f in sys.argv[1:]:\n    ast.parse(open(f,"rb").read(),f)', file]],
  '.sh': (file) => ['bash', ['-n', file]],
  '.js': (file) => ['node', ['--check', file]],
  '.mjs': (file) => ['node', ['--check', file]],
  '.cjs': (file) => ['node', ['--check', file]],
  '.go': (file) => ['gofmt', ['-e', '-l', file]],
};
const LANGUAGE_FILES = {
  python: ['.py'], bash: ['.sh'], recorded: ['.sh'], node: ['.js', '.mjs', '.cjs'], 'node-ts': ['.ts', '.mts', '.js', '.mjs'],
  tsx: ['.ts', '.tsx', '.js', '.mjs'], go: ['.go'], java: ['.java'],
};

let esbuild;
async function tsParse(file) {
  if (esbuild === undefined) {
    try {
      esbuild = await import(path.join(ROOT, 'node_modules', 'esbuild', 'lib', 'main.js'));
    } catch {
      esbuild = null;
    }
  }
  if (!esbuild) return 'esbuild (npm ci installs it)';
  const loader = file.endsWith('.tsx') ? 'tsx' : file.endsWith('.ts') || file.endsWith('.mts') ? 'ts' : 'js';
  try {
    (esbuild.default ?? esbuild).transformSync(fs.readFileSync(file, 'utf8'), { loader, sourcefile: file, format: 'esm' });
    return null;
  } catch (err) {
    return { error: err.message.split('\n').slice(0, 4).join('\n') };
  }
}

async function lintSyntax(problems, missing) {
  for (const entry of manifest()) {
    const lab = loadLab(entry);
    if (lab.mode === 'read-along' || lab.syntax === false) continue;
    // A recorded shell session is bash, whatever its extension.
    const exts = LANGUAGE_FILES[lab.runner] ?? [];
    const files = lab.files.filter((f) => f === lab.main && lab.runner === 'bash' ? true : exts.includes(path.extname(f)));
    const javaFiles = [];
    for (const name of files) {
      const file = path.join(lab.dir, 'starter', name);
      const where = `${lab.relDir}/starter/${name}`;
      const ext = path.extname(name);
      if (ext === '.java') { javaFiles.push(file); continue; }
      if (['.ts', '.tsx', '.mts'].includes(ext) || (['node-ts', 'tsx'].includes(lab.runner) && ['.js', '.mjs'].includes(ext))) {
        const res = await tsParse(file);
        if (typeof res === 'string') missing.add(res);
        else if (res) problems.push(`${where}: does not parse\n${res.error}`);
        continue;
      }
      const syntax = lab.runner === 'bash' ? SYNTAX['.sh'] : SYNTAX[ext];
      if (!syntax) continue;
      const [tool, args] = syntax(file);
      if (!which(tool)) { missing.add(tool); continue; }
      const res = spawnSync(tool, args, { encoding: 'utf8', env: { ...process.env, PATH: searchPath } });
      if (res.status !== 0) problems.push(`${where}: does not parse\n${(res.stderr || res.stdout).trim().split('\n').slice(-4).join('\n')}`);
    }
    if (javaFiles.length) {
      if (!which('javac')) { missing.add('javac'); continue; }
      // `java File.java` compiles that one file, whatever its public type is called; javac wants the file named
      // after it, so the check compiles a copy under that name.
      const source = fs.readFileSync(path.join(lab.dir, 'starter', lab.main), 'utf8');
      const type = /^\s*public\s+(?:(?:abstract|final|sealed|non-sealed|static|strictfp)\s+)*(?:class|record|interface|enum|@interface)\s+(\w+)/m.exec(source)?.[1];
      const out = fs.mkdtempSync(path.join(os.tmpdir(), 'learnsome-javac-'));
      const copy = path.join(out, `${type ?? path.basename(lab.main, '.java')}.java`);
      fs.writeFileSync(copy, source);
      const res = spawnSync('javac', ['-proc:none', '-nowarn', '-d', out, copy], { encoding: 'utf8' });
      fs.rmSync(out, { recursive: true, force: true });
      if (res.status !== 0) problems.push(`${lab.relDir}/starter/${lab.main}: does not compile\n${res.stderr.trim().split('\n').slice(0, 6).join('\n')}`);
    }
  }
}

async function lint({ strict }) {
  const problems = [];
  const missing = new Set();
  lintStructure(problems);
  await lintSyntax(problems, missing);
  // The checker labs: the starter must pass the site's checker (hadolint, actionlint, kubeconform...).
  let checked = 0;
  for (const entry of manifest()) {
    const lab = loadLab(entry);
    if (lab.mode !== 'checker') continue;
    const tools = missingTools(lab);
    if (tools.length) { tools.forEach((t) => missing.add(t)); continue; }
    const result = await execute(lab);
    checked++;
    if (result.exitCode !== 0 || result.timedOut) problems.push(`${lab.relDir}: ${lab.command} failed (exit ${result.exitCode})\n${(result.stdout + result.stderr).trim().split('\n').slice(0, 6).join('\n')}`);
  }
  for (const p of problems) console.log(`${STATUS.FAIL}  ${p}`);
  if (missing.size) console.log(`${strict ? STATUS.FAIL : STATUS.SKIP}  not checked, missing on PATH: ${[...missing].sort().join(', ')}`);
  const bad = problems.length + (strict ? missing.size : 0);
  console.log(`${manifest().length} labs: ${problems.length ? `${problems.length} problems` : 'structure and syntax OK'}${checked ? `, ${checked} checker labs run` : ''}`);
  return bad ? 1 : 0;
}

// ---------- main ----------

const HELP = `Usage:
  ./check <lab>...        run labs and compare with the expected output, as the site does
                          (<lab> is a lab id like ${COURSE.exampleLab}, a lesson id, or a path in a lab)
  ./check --all           every lab of the course
  ./check --list          the labs, and how each is checked
  ./check --lint          repository structure, starter syntax and checker labs (what CI runs)
Options: -v / --verbose shows the program's output; --strict (with --lint) fails when a tool is missing.`;

async function main() {
  const args = process.argv.slice(2);
  const flags = new Set(args.filter((a) => a.startsWith('-')));
  const names = args.filter((a) => !a.startsWith('-'));
  const unknown = [...flags].filter((f) => !['--all', '--list', '--lint', '--strict', '-v', '--verbose', '-h', '--help'].includes(f));
  if (flags.has('-h') || flags.has('--help') || unknown.length || (!names.length && !['--all', '--list', '--lint'].some((f) => flags.has(f)))) {
    if (unknown.length) console.error(`check: unknown option ${unknown.join(' ')}`);
    console.log(HELP);
    return unknown.length ? 2 : 0;
  }
  if (flags.has('--lint')) return lint({ strict: flags.has('--strict') });
  if (flags.has('--list')) {
    for (const entry of manifest()) {
      const lab = loadLab(entry);
      console.log(`${lab.lab.padEnd(14)} ${lab.mode.padEnd(10)} ${lab.command ?? ''}`);
    }
    return 0;
  }
  const entries = flags.has('--all') ? manifest() : select(names);
  const tally = { pass: 0, fail: 0, ran: 0, skip: 0, notool: 0 };
  for (const entry of entries) tally[await checkLab(loadLab(entry), { verbose: flags.has('-v') || flags.has('--verbose') || entries.length === 1 })]++;
  if (entries.length > 1) {
    console.log(`\n${tally.pass} passed, ${tally.fail} failed, ${tally.ran} ran without grading, ${tally.skip} read along${tally.notool ? `, ${tally.notool} not run (missing tool)` : ''}`);
  }
  return tally.fail ? 1 : tally.notool ? 2 : 0;
}

process.exitCode = await main();
