// The LearnSome.tech lab grader (workers/labs/src/grading.js on the platform), copied unchanged so ./check
// compares output exactly as the site does. Generated by the LearnSome.tech platform (scripts/labs-repos); do not edit here.
// Output grading, ported from the local API's former runner (backend/src/labs.js), plus the comparison rules
// of the courses whose tools print machine-specific noise (ansible, terraform, dotnet, git) or that compare in
// their own way (bash, and the testing course's pytest reports), ported from their own scripts/output.ts. Pure
// functions: the lab service grades in the Worker, never inside the sandbox.

/** Contract comparison: per-line trailing whitespace trimmed, trailing blank lines ignored. */
const normalizeLines = (text) =>
  text
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((line) => line.trimEnd())
    .join('\n')
    .replace(/\n+$/, '')
    .split('\n');

/**
 * The courses record expected.txt as stdout followed by stderr and compare it
 * with traceback scaffolding (File/source/caret lines) and blank lines set
 * aside, so intentional-error listings are graded the same way here.
 */
const courseNormalize = (text) =>
  text
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .filter((l) => !/^Traceback \(most recent call last\):\s*$/.test(l))
    .filter((l) => !/^\s+File ".*", line \d+/.test(l))
    .filter((l) => !/^\s*[\^~]+\s*$/.test(l))
    .filter((l) => !/^\s{4}\S/.test(l))
    .map((l) => l.trimEnd())
    .filter((l) => l !== '')
    .join('\n');

const MAX_DIFF = 200;

function lineDiff(actualText, expectedText) {
  const actual = normalizeLines(actualText);
  const expected = normalizeLines(expectedText);
  const diff = [];
  const n = Math.max(actual.length, expected.length);
  for (let i = 0; i < n && diff.length < MAX_DIFF; i++) {
    if (actual[i] !== expected[i]) diff.push({ line: i + 1, expected: expected[i] ?? null, actual: actual[i] ?? null });
  }
  return diff;
}

// sqlite3 builds differ in column alignment and float printing, so SQL result
// sets are compared cell by cell (the sql course's own comparison rules).
const sqlError = (line) =>
  line
    .replace(/^(?:Runtime error|Error|Parse error)(?: near line \d+)?: (.*?)(?: \(\d+\))?$/, 'ERROR: $1')
    .replace(/\s+/g, ' ')
    .trim();
const sqlCells = (line) => line.trim().split(/\s{2,}/).filter(Boolean);

function sqlCellEquals(a, b) {
  if (a === b) return true;
  const x = Number(a);
  const y = Number(b);
  return a !== '' && b !== '' && !Number.isNaN(x) && !Number.isNaN(y) && Math.abs(x - y) < 1e-4;
}

function sqlLineEquals(exp, act) {
  if (exp === act) return true;
  const e = sqlError(exp);
  if (e.startsWith('ERROR:') && e === sqlError(act)) return true;
  if (/^[- ]+$/.test(exp) && /^[- ]+$/.test(act)) return true;
  const ec = sqlCells(exp);
  const ac = sqlCells(act);
  return ec.length > 0 && ec.length === ac.length && ec.every((c, i) => sqlCellEquals(c, ac[i]));
}

function sqlSameOutput(expectedText, actualText) {
  const clean = (t) =>
    t
      .replace(/\r\n?/g, '\n')
      .split('\n')
      .map((l) => l.trimEnd())
      .filter((l) => l.trim() !== '');
  const exp = clean(expectedText);
  const act = clean(actualText);
  return exp.length === act.length && exp.every((line, i) => sqlLineEquals(line, act[i]));
}

const ANSI = /\u001b\[[0-9;?]*[A-Za-z]/g;

// ansible-course scripts/output.ts: banner padding and column alignment collapsed, the machine's own
// warnings (and their wrapped continuation lines) dropped, blank lines ignored.
const ANSIBLE_WARNING_START = /^\s*\[(?:WARNING|DEPRECATION WARNING|NOTICE)\]/;
const ANSIBLE_ROW = /^(?:PLAY|TASK|RUNNING HANDLER|HANDLER|ok:|changed:|failed:|fatal:|skipping:|ignoring:|included:|localhost|---|\+\+\+|@@)/;
const ANSIBLE_ENVIRONMENTAL = [
  /^\s*\[WARNING\]/,
  /^\s*\[DEPRECATION WARNING\]/,
  /^You are using/,
  /^\s*no action detected in task/,
  /Python interpreter/,
  /^\s*See https:\/\/docs\.ansible\.com/,
];

function ansibleNormalize(text) {
  const out = [];
  let inWarning = false;
  for (const raw of text.replace(/\r\n?/g, '\n').split('\n')) {
    const line = raw.replace(ANSI, '');
    if (ANSIBLE_WARNING_START.test(line)) {
      inWarning = true;
      continue;
    }
    if (inWarning) {
      if (!ANSIBLE_ROW.test(line)) continue;
      inWarning = false;
    }
    if (ANSIBLE_ENVIRONMENTAL.some((re) => re.test(line))) continue;
    const collapsed = line.replace(/\*{2,}/g, '***').replace(/={3,}/g, '===').replace(/\s+/g, ' ').trim();
    if (collapsed !== '') out.push(collapsed);
  }
  return out;
}

// terraform-course scripts/output.ts: plugin-installation lines and advisory prose dropped, ids, versions,
// durations, timestamps and working directories masked, colour and blank lines ignored.
const TERRAFORM_NOISE = [
  /^- Finding /,
  /^- Installing /,
  /^- Installed /,
  /^- Using /,
  /^- Reusing previous version of /,
  /^- Downloading /,
  /^Initializing provider plugins\.\.\.$/,
  /^Initializing modules\.\.\.$/,
  /^Initializing the backend\.\.\.$/,
  /^Terraform has created a lock file/,
  /^selections it made above\./,
  /^so that Terraform can guarantee/,
  /^you run "terraform init" in the future\./,
  /^Your version of Terraform is out of date/,
  /^is \d+\.\d+\.\d+\. You can update by downloading/,
  /^Terraform used the selected providers to generate the following execution$/,
  /^plan\. Resource actions are indicated with the following symbols:$/,
  /^Terraform has compared your real infrastructure against your$/,
  /^configuration and found no differences, so no changes are needed\.$/,
  /^Terraform has compared your real infrastructure against your configuration$/,
  /^and found no differences, so no changes are needed\.$/,
  /\[\d+s elapsed\]$/,
  /^Acquiring state lock\./,
  /^Releasing state lock\./,
  /^Stopping operation\.\.\./,
];

const terraformMask = (line) =>
  line
    .replace(/\[id=[^\]]*\]/g, '[id=ID]')
    .replace(/\bid *= *"[^"]*"/g, 'id = "ID"')
    .replace(/\bafter (?:\d+m)?\d+s\b/g, 'after Ns')
    .replace(/\bv\d+\.\d+\.\d+\b/g, 'vX.Y.Z')
    .replace(/\b20\d\d-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z?\b/g, 'TIMESTAMP')
    .replace(/\/(?:private\/)?(?:var|tmp)\/[\w./-]*tfcourse-[\w./-]*/g, 'WORKDIR')
    .replace(/\/(?:private\/)?var\/folders\/[\w./+-]+/g, 'WORKDIR');

const terraformNormalize = (text) =>
  text
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((l) => l.replace(ANSI, '').trimEnd())
    .filter((l) => l !== '' && !TERRAFORM_NOISE.some((re) => re.test(l)))
    .map(terraformMask);

// dotnet-course scripts/output.ts: the SDK's restore, build and test-platform banners, Kestrel's start-up
// lines and stack-trace frames dropped; times, paths, guids and timestamps masked; blank lines ignored.
const DOTNET_NOISE = [
  /^\s*Determining projects to restore\.{3}\s*$/,
  /^\s*All projects are up-to-date for restore\.\s*$/,
  /^\s*Restored .*$/,
  /^\s*Restore complete.*$/,
  /^\s*Restore succeeded.*$/,
  /^\s*Nothing to do\. None of the projects specified contain packages to restore\.\s*$/,
  /^\s*MSBuild version .*$/,
  /^\s*Welcome to \.NET.*$/,
  /^\s*-{3,}.*$/,
  /^\s*Telemetry\b.*$/,
  /^\s*Learn (?:more|about) .*$/,
  /^\s*Build succeeded(?: in .*)?\.?\s*$/,
  /^\s*Build succeeded with .*$/,
  /^\s*\d+ Warning\(s\)\s*$/,
  /^\s*\d+ Error\(s\)\s*$/,
  /^\s*Time Elapsed .*$/,
  /^\s*Elapsed time: .*$/,
  /^\s*\S+ -> \/.*\.(?:dll|exe)\s*$/,
  /^\s*Microsoft \(R\) Test Execution Command Line Tool.*$/,
  /^\s*Copyright \(c\) Microsoft Corporation\..*$/,
  /^\s*Starting test execution, please wait\.{3}\s*$/,
  /^\s*A total of \d+ test files matched the specified pattern\.\s*$/,
  /^\s*VSTest version .*$/,
  /^\s*Test run for .*$/,
  /^\s*Results File: .*$/,
  /^\s*info: Microsoft\.Hosting\.Lifetime.*$/,
  /^\s*Now listening on: .*$/,
  /^\s*Application started\. Press Ctrl\+C to shut down\.\s*$/,
  /^\s*Hosting environment: .*$/,
  /^\s*Content root path: .*$/,
  /^\s+at .+$/,
  /^\s*--- End of stack trace from previous location ---\s*$/,
];
const DOTNET_UNSTABLE = [
  [/\b\d+(?:[.,]\d+)?\s?(?:ms|s|sec|secs|seconds|m)\b/g, 'TIME'],
  [/(?:\/[\w.@+-]+){2,}/g, 'PATH'],
  [/[A-Za-z]:\\[\w.\\@+-]+/g, 'PATH'],
  [/\b[0-9a-fA-F]{8}-(?:[0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\b/g, 'GUID'],
  [/\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?/g, 'TIMESTAMP'],
];

const dotnetNormalize = (text) =>
  text
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((l) => l.replace(ANSI, ''))
    .filter((l) => !DOTNET_NOISE.some((re) => re.test(l)))
    .map((l) => DOTNET_UNSTABLE.reduce((acc, [re, to]) => acc.replace(re, to), l).replace(/\s+$/, ''))
    .filter((l) => l !== '');

// bash-course scripts/output.ts: every line compared, blank lines in the middle included (in shell output they
// are content); only trailing whitespace and the blank lines before the first and after the last line of
// output, which come from how a snippet is fed to the shell, are set aside.
function bashNormalize(text) {
  const lines = text.replace(/\r\n?/g, '\n').split('\n').map((l) => l.replace(/\s+$/, ''));
  let first = 0;
  let last = lines.length;
  while (first < last && lines[first] === '') first += 1;
  while (last > first && lines[last - 1] === '') last -= 1;
  return lines.slice(first, last);
}

// git-course scripts/output.ts: object ids, human dates, temporary directories, pack sizes and the git
// version masked, blank lines ignored. Plus what only the git release changes, never a lesson's point: the
// `hint:` advice lines (reworded between releases) and the column padding of `wc`'s counts (BSD pads, GNU
// does not).
const GIT_OBJECT_ID = /\b[0-9a-f]{7,40}\b/g;

const gitNormalize = (text) =>
  text
    .replace(/\r\n?/g, '\n')
    .split('\n')
    .map((l) => l.replace(ANSI, '').replace(/\s+$/, ''))
    .filter((l) => !/^hint:/.test(l))
    .map((l) => l.replace(/\/(?:private\/)?(?:var|tmp)\/[^\s'")]*gitcourse-[A-Za-z0-9]+[^\s'")]*/g, '<dir>'))
    .map((l) => l.replace(/\/(?:private\/)?(?:var|tmp)\/[A-Za-z0-9._/-]+/g, '<dir>'))
    .map((l) => l.replace(/^((?:Author|Commit)?Date:\s+).*$/, '$1<date>'))
    .map((l) => l.replace(/\b[A-Z][a-z]{2} [A-Z][a-z]{2} \d{1,2} \d\d:\d\d:\d\d \d{4} [-+]\d{4}\b/g, '<date>'))
    .map((l) => l.replace(/\b\d{4}-\d\d-\d\d[ T]\d\d:\d\d(:\d\d)?( [-+]\d{4})?\b/g, '<date>'))
    .map((l) => l.replace(/\b\d+ (?:seconds?|minutes?|hours?|days?|weeks?|months?|years?) ago\b/g, '<date>'))
    .map((l) => l.replace(GIT_OBJECT_ID, '<id>'))
    .map((l) => l.replace(/\b\d+(\.\d+)? [KMG]?i?B(\/s)?\b/g, '<size>'))
    .map((l) => l.replace(/^git version .*$/, 'git version <version>'))
    .map((l) => l.replace(/^\s+(\d+)(?=\s)/, '$1'))
    .filter((l) => l !== '');

// A pytest report is graded on its outcome, not its text: which tests passed, failed or errored (the -v
// rows, the short summary's FAILED/ERROR rows, the ids --collect-only lists) and the final tally. Timings,
// the terminal width, the platform header and the tracebacks' wording belong to the machine and the pytest
// release. Warnings are not an outcome.
const PYTEST_TALLY = /^=*\s*((?:\d+(?:\/\d+)? (?:passed|failed|errors?|skipped|xfailed|xpassed|deselected|warnings?|rerun|tests? collected)(?: \(\d+ deselected\))?(?:, )?)+|no tests ran)(?: in (?:[\d.]+|TIME)s(?: \(\d+:\d\d:\d\d\))?)?\s*=*$/;
const PYTEST_ROW = /^(\S+::\S+?)\s+(PASSED|FAILED|ERROR|SKIPPED|XFAIL|XPASS)\b/;
const PYTEST_SUMMARY_ROW = /^(FAILED|ERROR|XFAIL|XPASS|SKIPPED)\s+(\S+::\S+|\S+\.py)(?:\s|$)/;
const PYTEST_COLLECTED = /^(?:<[^>]+>\s*)*(\S+\.py::\S+)$/;

function pytestOutcome(text) {
  const tests = new Set();
  let tally = null;
  for (const raw of text.replace(/\r\n?/g, '\n').split('\n')) {
    const line = raw.replace(ANSI, '').trim();
    const row = PYTEST_ROW.exec(line);
    if (row) { tests.add(`${row[1]} ${row[2]}`); continue; }
    const summary = PYTEST_SUMMARY_ROW.exec(line);
    if (summary) { tests.add(`${summary[2]} ${summary[1]}`); continue; }
    const collected = PYTEST_COLLECTED.exec(line);
    if (collected) { tests.add(`${collected[1]} COLLECTED`); continue; }
    const m = PYTEST_TALLY.exec(line);
    if (m) {
      tally = m[1]
        .split(', ')
        .filter((part) => !/warnings?$/.test(part))
        .join(', ');
    }
  }
  return tally === null ? null : [...[...tests].sort(), `tally: ${tally}`];
}

/** Compares two pytest reports by outcome; a report without a final tally is compared as text. */
function pytestGrade(stdout, stderr, expectedText) {
  const expected = pytestOutcome(expectedText);
  const actual = pytestOutcome(stdout + stderr);
  if (expected === null) return { passed: false, diff: lineDiff(stdout + stderr, expectedText) };
  const got = actual ?? [];
  const diff = [];
  for (let i = 0; i < Math.max(got.length, expected.length) && diff.length < MAX_DIFF; i++) {
    if (got[i] !== expected[i]) diff.push({ line: i + 1, expected: expected[i] ?? null, actual: got[i] ?? null });
  }
  return { passed: diff.length === 0, diff };
}

/** Compares stdout + stderr with the expected output after a course's own normalization. */
function normalizedGrade(normalize, stdout, stderr, expectedText) {
  const expected = normalize(expectedText);
  const actual = normalize(stdout + stderr);
  const diff = [];
  for (let i = 0; i < Math.max(actual.length, expected.length) && diff.length < MAX_DIFF; i++) {
    if (actual[i] !== expected[i]) diff.push({ line: i + 1, expected: expected[i] ?? null, actual: actual[i] ?? null });
  }
  return { passed: diff.length === 0, diff };
}

/**
 * The expected output recorded in a shell-session listing: the commented lines under each command
 * (`#   text`, `#` alone for a blank line), after the header comment that explains the file.
 */
export function transcriptExpected(source) {
  const out = [];
  let started = false;
  for (const line of source.replace(/\r\n?/g, '\n').split('\n')) {
    if (!started) {
      started = line.trim() !== '' && !line.startsWith('#');
      continue;
    }
    const m = /^#(?: {3}(.*)| *)$/.exec(line);
    if (m) out.push(m[1] ?? '');
  }
  return out.length ? `${out.join('\n')}\n` : '';
}

/**
 * Stdout alone is compared first; when that differs, stdout followed by stderr is compared under the
 * courses' own rules (expected.txt is recorded as stdout + stderr). The smaller diff is reported.
 * `grading` (the lab index's) picks a course's comparison: SQL result sets cell by cell, ansible, terraform,
 * .NET and git output with their machine-specific noise set aside, pytest reports by their outcome, and a
 * replayed >>> session (`repl`: errors in place on stdout) under the courses' rules for tracebacks even though
 * nothing went to stderr.
 */
export function gradeOutput(stdout, stderr, expectedText, { grading = 'lines' } = {}) {
  if (grading === 'ansible') return normalizedGrade(ansibleNormalize, stdout, stderr, expectedText);
  if (grading === 'terraform') return normalizedGrade(terraformNormalize, stdout, stderr, expectedText);
  if (grading === 'dotnet') return normalizedGrade(dotnetNormalize, stdout, stderr, expectedText);
  if (grading === 'git') return normalizedGrade(gitNormalize, stdout, stderr, expectedText);
  if (grading === 'bash') return normalizedGrade(bashNormalize, stdout, stderr, expectedText);
  if (grading === 'pytest') return pytestGrade(stdout, stderr, expectedText);
  const stdoutDiff = lineDiff(stdout, expectedText);
  if (stdoutDiff.length === 0) return { passed: true, diff: [] };
  const combined = stdout + stderr;
  if (grading === 'sql' && sqlSameOutput(expectedText, combined)) return { passed: true, diff: [] };
  if (!stderr && grading !== 'repl') return { passed: false, diff: stdoutDiff };
  if (courseNormalize(combined) === courseNormalize(expectedText)) return { passed: true, diff: [] };
  const combinedDiff = lineDiff(combined, expectedText);
  return { passed: false, diff: combinedDiff.length < stdoutDiff.length ? combinedDiff : stdoutDiff };
}
